
export { default as BookOpen } from './BookOpen'
export { default as Calendar } from './Calendar'
export { default as ClockAlt } from './ClockAlt'
export { default as Copy } from './Copy'
export { default as Envelope } from './Envelope'
export { default as Globe } from './Globe'
export { default as GraduationCap } from './GraduationCap'
export { default as Lock } from './Lock'
export { default as MoneyBill } from './MoneyBill'
export { default as Upload } from './Upload'